### ISSUE TITLE
Install scrooge on vps ubuntu

### ISSUE THREAD

**Issue by ingnelson** [rafaelcaricio/scrooge#1]
Hello sir.

can you tell me the command to install and run scrooge server on a ubuntu vps , please ? 
what do i do when after this commands ?

apt install git curl wget vim -y 
git clone https://github.com/rafaelcaricio/scrooge.git

can you give me the next commands , please ? 
do i need any other package ?
can i use bytes instead MB ?

please i need to use this proxy server.

i will await your answer.

**Comment by rafaelcaricio** [comment]
Hi,

You will need to install the Rust toolchain and compile from source. The easiest way to install the necessary tools is using https://rustup.rs/

After rustup is installed, you can just go to the directory where you cloned `scrooge` and run this command:

```sh
cargo install --path .
```
All dependencies will be downloaded, compiled, installed. After that command successfully terminates. `scrooge` binary will be available at the path `~/.cargo/bin/scrooge`

> can i use bytes instead MB ?

Yes, you can use any of: B, kB, MB, GB, TB.

**Comment by ingnelson** [comment]
@rafaelcaricio 
  i run it , but one more question :

is it posible to run scrooge and listen only  0.0.0.0  and not http://0.0.0.0:80  
so i can use my pc or android as a client and send the http request i want to  . 

add option #1
 the client send a http request and  the "http path" have this two parameter #0=  and bytesize=   :
EXAMPLE: 
server on the vps : 
scrooge listen on 0.0.0.0  on port 80

client android or pc send the http request with GET or HEAD or POST or DELETE  :
GET #0=password&bytesize=1000# HTTP/1,1\r\n
Host: www.example.com/\r\n\r\n

bytesize=    tell to the server the bytes want the server send back to the client.

Note: i just have a android app that works as a http client and it calculate the bytes download (bytes send by the server)
the more importan think it is the server undestand the 2 parameter on the path and by default always beging and finish with a symbol #

can you create it , please ? .  

i really need this option.

**Comment by rafaelcaricio** [comment]
Please open a pull request for your changes. I cannot work on that for you.
